### ISSUE TITLE
🎱 Store picks in localStorage

### ISSUE THREAD

**Issue by jefftriplett** [bmispelon/jeffbingo#12]
localStorage support would make it easier to refresh the card and store picks. 

https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage

**Comment by alexgmin** [comment]
I think the most optimal solution is to store the bingo html in the localStorage

**Comment by bmispelon** [comment]
> I think the most optimal solution is to store the bingo html in the localStorage

🤯
