### ISSUE TITLE
Keyboards and 8bitdo update? 

### ISSUE THREAD

**Issue by jefftriplett** [bmispelon/jeffbingo#2]
We talk way too much about keyboards and video game controllers https://www.8bitdo.com merch to not have on our list.

**Comment by alexgmin** [comment]
Other than the bring your keyboard to class day I don't remember more, but controllers have been mentioned enough, so let's add a "Keyboard or controller talk"

**Comment by MHLut** [comment]
"Keyboard show-off"

**Comment by bmispelon** [comment]
Who told Jeff about this? 😮

**Comment by MHLut** [comment]
@bmispelon Not me!

**Comment by jefftriplett** [comment]
> Who told Jeff about this? 😮

I see everything, Baptiste. (fake blames/frames @MHLut as the weak link)
