### ISSUE TITLE
Specify the Chris's

### ISSUE THREAD

**Issue by MHLut** [bmispelon/jeffbingo#3]
Since we have multiple Chris's with an entry, shall we specify their names a bit more?

* "Chris M. fireworks camera effect";
* "Chris R. talks about Ruby".

**Comment by alexgmin** [comment]
On a serious project, I'd agree. But for shitposting purposes, I think it's a bit funnier if you don't specify which one.

**Comment by bmispelon** [comment]
> On a serious project, I'd agree. But for shitposting purposes, I think it's a bit funnier if you don't specify which one.

This **is** a serious project, what do you mean?

I think I'd rather keep the Chrises first-name-only, because it makes the text shorter and it gives more chances for people to win in the case the wrong Chris starts talking about Ruby 😁 
(but i don't have strong feelings)

**Comment by MHLut** [comment]
We'll leave it as-is; it's less effort, and that's also good. 😂
